package terraform

const BACKEND_TEMPLATE = `
# This file is generated by jinn-tf and ignore from repo.
# Please do not try to change, it'll be reset for every terraform command triggered from jinn-tf
terraform {
  backend "s3" {
    bucket                  = "{{.StateBucket}}"
    key                     = "{{.StateFilePath}}"
    region                  = "{{.AwsRegion}}"
    shared_credentials_file = "$HOME/.aws/credentials"
    profile                 = "{{.AwsProfile}}"
  }
}

locals {
  environment = "{{.Environment}}"
}
`
